# This flag tells the Android plugin to use the AndroidX libraries.
# This is what the safeargs plugin is looking for.
android.useAndroidX=true

# This flag automatically migrates any old support libraries 
# from third-party dependencies to their AndroidX equivalents.
android.enableJetifier=true

# Increase VM memory for Gradle to improve build performance
org.gradle.jvmargs=-Xmx2048m